@echo off
echo Downloading Naruto Keyboard...
curl -L -o public/naruto_kb.png "https://m.media-amazon.com/images/I/71z7-zNnK7L._AC_SL1500_.jpg"
echo Downloading Free Fire Keyboard...
curl -L -o public/freefire_kb.png "https://m.media-amazon.com/images/I/71-SjN-Z8BL._AC_SL1500_.jpg"
echo Downloading Gamer Pack...
curl -L -o public/gamer_pack.png "https://m.media-amazon.com/images/I/71+6VvD0XFL._AC_SL1500_.jpg"
echo Downloading PUBG Tiffany Edition...
curl -L -o public/pubg_bundle.png "https://images.unsplash.com/photo-1614149162883-504ce4d13909?auto=format&fit=crop&q=80&w=800"
echo Done! All images downloaded to public folder.
pause
